### ISSUE TITLE
setup.py and setup.cfg metadata is inconsistent

### ISSUE THREAD

**Issue by bnavigator** [jupyter/nbclassic#135]
I see you copied over the notebook 6 setup.py to nbclassic. Now there are two files with inconsistend metadata in the repository.

**Comment by echarles** [comment]
The `setup.cfg` is only use by the Check Release CI job to generate a hash for the `key`. The log says e.g. 

```
  with:
    path: /home/runner/.cache/pip
    key: Linux-pip-0af18be079638b7a6856559a469eb62f0aa39d3065d0668e8b50af56daa98de3
    restore-keys: Linux-pip-
  Linux-pip-
```

`setup.cfg` is also bundled in the `SOURCES.txt`.

Would it be OK to simply remove `setup.cfg` and use `setup.py` to generate the hash?
